/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_takip;

import java.awt.Toolkit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JFrm_CalisanAra extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_AramaIslemleri
     */
    DefaultTableModel dtm = new DefaultTableModel();
    List<Calisan_1> calisanlar;

    public JFrm_CalisanAra() {
        initComponents();
         setTitle(JFrm_GirisEkrani.y_logined.getYoneticiAdi() + " " + JFrm_GirisEkrani.y_logined.getYoneticiSoyadi());
        Toolkit kit = Toolkit.getDefaultToolkit();
        int EkranY = (int) kit.getScreenSize().width; //Ekran boyutunun genişliğini alıyoruz...
        int EkranX = (int) kit.getScreenSize().height;//Ekran boyutunun yüksekliğini alıyoruz...
        this.setSize(775, 463); // Pencere boyutunu belirliyoruz...
        this.setLocation((EkranY - 775) / 2, (EkranX - 463) / 2);
        jTable1.setVisible(false);
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRbtn_kullanicilarimda = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRbtn_tümkullanicilarda = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));

        buttonGroup1.add(jRbtn_kullanicilarimda);
        jRbtn_kullanicilarimda.setText("Kullanıcılarımda Ara");
        jRbtn_kullanicilarimda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_kullanicilarimdaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel1.setText("ARANACAK KELİME       :");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRbtn_tümkullanicilarda);
        jRbtn_tümkullanicilarda.setText("Tüm Kullanıcılarda Ara");
        jRbtn_tümkullanicilarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_tümkullanicilardaActionPerformed(evt);
            }
        });

        jMenu1.setText("Geri Dön");

        jMenuItem1.setText("Geri Dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jRbtn_kullanicilarimda)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbtn_tümkullanicilarda)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRbtn_kullanicilarimda)
                    .addComponent(jRbtn_tümkullanicilarda))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRbtn_kullanicilarimdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_kullanicilarimdaActionPerformed
        // TODO add your handling code here:
        dtm.setColumnIdentifiers(new String[]{"Çalışan Id", "Çalışan Adı", "Çalışan Soyadı"});
        dtm.setRowCount(0);
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir kelime giriniz!");
        } else {
            jTable1.setVisible(true);
            int sayac1 = 0;

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");

            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("SELECT c FROM Calisan_1 c WHERE c.yoneticiId = :id");
            
            q.setParameter("id", JFrm_GirisEkrani.y_logined.getYoneticiId());
            calisanlar = q.getResultList();
            for (Calisan_1 calisan : calisanlar) {
                if (calisan.getCalisanAdi().toLowerCase().startsWith(jTextField1.getText().toLowerCase()) || calisan.getCalisanSoyadi().toLowerCase().startsWith(jTextField1.getText().toLowerCase())) {
                    sayac1++;
                    dtm.addRow(new Object[]{calisan.getCalisanId(), calisan.getCalisanAdi(), calisan.getCalisanSoyadi()});
                }

            }
            if (sayac1 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Arama ile eşleşen sonuç yok.");
            }
        }
    }//GEN-LAST:event_jRbtn_kullanicilarimdaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrm_YoneticiEkrani newyoneticiekrani = new JFrm_YoneticiEkrani();
        newyoneticiekrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        dtm.setRowCount(0);
        jRbtn_kullanicilarimda.setSelected(false);
        jRbtn_tümkullanicilarda.setSelected(false);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jRbtn_tümkullanicilardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_tümkullanicilardaActionPerformed
        // TODO add your handling code here:
        dtm.setColumnIdentifiers(new String[]{"Çalışan Id", "Çalışan Adı", "Çalışan Soyadı", "Çalışan Yöneticisi Id"});
        dtm.setRowCount(0);
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir kelime giriniz!");
        }else {
            jTable1.setVisible(true);
            int sayac2 = 0;

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");

            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("SELECT c FROM Calisan_1 c ");
            
            calisanlar = q.getResultList();
            for (Calisan_1 calisan : calisanlar) {
                if (calisan.getCalisanAdi().toLowerCase().startsWith(jTextField1.getText().toLowerCase()) || calisan.getCalisanSoyadi().toLowerCase().startsWith(jTextField1.getText().toLowerCase())) {
                    sayac2++;
                    dtm.addRow(new Object[]{calisan.getCalisanId(), calisan.getCalisanAdi(), calisan.getCalisanSoyadi(), calisan.getYoneticiId()});
                }

            }
            if (sayac2 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Arama ile eşleşen sonuç yok.");
            }
        }
    }//GEN-LAST:event_jRbtn_tümkullanicilardaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisanAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisanAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisanAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisanAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_CalisanAra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRbtn_kullanicilarimda;
    private javax.swing.JRadioButton jRbtn_tümkullanicilarda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
