/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_takip;

import java.awt.Toolkit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JFrm_CalisaninGörevleriniFiltrele extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DefaultTableModel dtm = new DefaultTableModel();

    public JFrm_CalisaninGörevleriniFiltrele() {
        initComponents();
        setTitle(JFrm_GirisEkrani.y_logined.getYoneticiAdi() + " " + JFrm_GirisEkrani.y_logined.getYoneticiSoyadi());
        Toolkit kit = Toolkit.getDefaultToolkit();
        int EkranY = (int) kit.getScreenSize().width; //Ekran boyutunun genişliğini alıyoruz...
        int EkranX = (int) kit.getScreenSize().height;//Ekran boyutunun yüksekliğini alıyoruz...
        this.setSize(570, 530); // Pencere boyutunu belirliyoruz...
        this.setLocation((EkranY - 570) / 2, (EkranX - 530) / 2);
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[]{"Görev Id", "Görev Adı", "Proje Id"});

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
        EntityManager em = emf.createEntityManager();

        Query q1 = em.createQuery("SELECT c FROM Calisan_1 c WHERE c.yoneticiId = :id");
        q1.setParameter("id", JFrm_GirisEkrani.y_logined.getYoneticiId());
        List<Calisan_1> calisanlar = q1.getResultList();

        for (Calisan_1 calisan : calisanlar) {
            jComboBox1.addItem(calisan);
        }

        jComboBox1.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRbtn_teslimEdilmemis = new javax.swing.JRadioButton();
        jRbtn_teslimEdilmis = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel1.setText("çalışan Id    :");

        buttonGroup1.add(jRbtn_teslimEdilmemis);
        jRbtn_teslimEdilmemis.setText("Teslim Edilmemiş Görevler");
        jRbtn_teslimEdilmemis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_teslimEdilmemisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbtn_teslimEdilmis);
        jRbtn_teslimEdilmis.setText("Teslim Edilmiş Görevler");
        jRbtn_teslimEdilmis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_teslimEdilmisActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Geri Dön");

        jMenuItem1.setText("Geri Dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jRbtn_teslimEdilmis)
                                .addGap(21, 21, 21)
                                .addComponent(jRbtn_teslimEdilmemis))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRbtn_teslimEdilmis)
                    .addComponent(jRbtn_teslimEdilmemis))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrm_YoneticiEkrani newyoneticiekrani = new JFrm_YoneticiEkrani();
        newyoneticiekrani.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jRbtn_teslimEdilmisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_teslimEdilmisActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);

        Calisan_1 secilenCalisan = (Calisan_1) jComboBox1.getSelectedItem();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
        EntityManager em = emf.createEntityManager();

        Query q1 = em.createQuery("SELECT g FROM Gorev_1 g WHERE g.calisanId = :id");
        q1.setParameter("id", secilenCalisan.getCalisanId());
        List<Gorev_1> gorevler = q1.getResultList();

        dtm.setRowCount(0);
        for (Gorev_1 gorev : gorevler) {
            if (gorev.getGorevTeslimTarihi() != null) {
                dtm.addRow(new Object[]{gorev.getGorevId(), gorev.getGorevAdi(), gorev.getProjeId()});
            }
        }
        
        if(dtm.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "Seçtiğiniz çalışanın teslim edilmiş projesi bulunmamaktadır.");
        }

    }//GEN-LAST:event_jRbtn_teslimEdilmisActionPerformed

    private void jRbtn_teslimEdilmemisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_teslimEdilmemisActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);

        Calisan_1 secilenCalisan = (Calisan_1) jComboBox1.getSelectedItem();

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
        EntityManager em = emf.createEntityManager();

        Query q1 = em.createQuery("SELECT g FROM Gorev_1 g WHERE g.calisanId = :id");
        q1.setParameter("id", secilenCalisan.getCalisanId());
        List<Gorev_1> gorevler = q1.getResultList();

        dtm.setRowCount(0);
        for (Gorev_1 gorev : gorevler) {
            if (gorev.getGorevTeslimTarihi() == null) {
                dtm.addRow(new Object[]{gorev.getGorevId(), gorev.getGorevAdi(), gorev.getProjeId()});
            }
        }
        
            if(dtm.getRowCount()==0){
            JOptionPane.showMessageDialog(rootPane, "Seçtiğiniz çalışanın teslim edilmemiş projesi bulunmamaktadır.");
        }
//      
    }//GEN-LAST:event_jRbtn_teslimEdilmemisActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisaninGörevleriniFiltrele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisaninGörevleriniFiltrele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisaninGörevleriniFiltrele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_CalisaninGörevleriniFiltrele.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_CalisaninGörevleriniFiltrele().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Calisan_1> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRbtn_teslimEdilmemis;
    private javax.swing.JRadioButton jRbtn_teslimEdilmis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
