/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_takip;

import java.awt.Toolkit;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JFrm_ProjeAra extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_ProjeAra
     */
    DefaultTableModel dtm = new DefaultTableModel();

    List<Proje_1> projeler;

    public JFrm_ProjeAra() {
        initComponents();
        setTitle(JFrm_GirisEkrani.y_logined.getYoneticiAdi() + " " + JFrm_GirisEkrani.y_logined.getYoneticiSoyadi());
        Toolkit kit = Toolkit.getDefaultToolkit();
        int EkranY = (int) kit.getScreenSize().width; //Ekran boyutunun genişliğini alıyoruz...
        int EkranX = (int) kit.getScreenSize().height;//Ekran boyutunun yüksekliğini alıyoruz...
        this.setSize(750, 500); // Pencere boyutunu belirliyoruz...
        this.setLocation((EkranY - 750) / 2, (EkranX - 500) / 2);
        jTable1.setVisible(false);
        jTable1.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRbtn_projelerimde = new javax.swing.JRadioButton();
        jRbtn_tümprojelerde = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRbtn_projelerimde);
        jRbtn_projelerimde.setText("Projelerimde Ara");
        jRbtn_projelerimde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_projelerimdeActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRbtn_tümprojelerde);
        jRbtn_tümprojelerde.setText("Tüm Projelerde Ara");
        jRbtn_tümprojelerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtn_tümprojelerdeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel1.setText("ARANACAK KELİME        :");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("Geri Dön");

        jMenuItem1.setText("Geri Dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRbtn_projelerimde)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRbtn_tümprojelerde)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtn_projelerimde)
                    .addComponent(jRbtn_tümprojelerde))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRbtn_projelerimdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_projelerimdeActionPerformed
        // TODO add your handling code here:
        dtm.setColumnIdentifiers(new String[]{"Proje Id", "Proje Adı"});
        dtm.setRowCount(0);
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir kelime giriniz veya arama seçeneğinizi belirtiniz!");
        } else {
            jTable1.setVisible(true);
            dtm.setRowCount(0);
            int sayac1 = 0;

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("SELECT p FROM Proje_1 p WHERE p.yoneticiId = :id");
            q.setParameter("id", JFrm_GirisEkrani.y_logined.getYoneticiId());

            projeler = q.getResultList();

            for (Proje_1 proje : projeler) {
                if (proje.getProjeAdi().toLowerCase().startsWith(jTextField1.getText().toLowerCase())) {
                    sayac1++;
                    dtm.addRow(new Object[]{proje.getProjeId(), proje.getProjeAdi(), proje.getYoneticiId()});
                }
            }
            if (sayac1 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Arama ile eşleşen sonuç yok.");
            }
        }
    }//GEN-LAST:event_jRbtn_projelerimdeActionPerformed

    private void jRbtn_tümprojelerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtn_tümprojelerdeActionPerformed
        // TODO add your handling code here:
        dtm.setColumnIdentifiers(new String[]{"Proje Id", "Proje Adı", "Proje Yöneticisi Id"});
        dtm.setRowCount(0);
        if (jTextField1.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Bir kelime giriniz veya arama seçeneğinizi belirtiniz!");
        } else {
            jTable1.setVisible(true);
            dtm.setRowCount(0);
            int sayac2 = 0;
            
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("SELECT p FROM Proje_1 p");

            projeler = q.getResultList();

            for (Proje_1 proje : projeler) {
                if (proje.getProjeAdi().toLowerCase().startsWith(jTextField1.getText().toLowerCase())) {
                    sayac2++;
                    dtm.addRow(new Object[]{proje.getProjeId(), proje.getProjeAdi(), proje.getYoneticiId()});
                }
            }
            if (sayac2 == 0) {
                JOptionPane.showMessageDialog(rootPane, "Arama ile eşleşen sonuç yok.");
            }
        }
    }//GEN-LAST:event_jRbtn_tümprojelerdeActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        dtm.setRowCount(0);
        jRbtn_projelerimde.setSelected(false);
        jRbtn_tümprojelerde.setSelected(false);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrm_YoneticiEkrani newyoneticiekrani = new JFrm_YoneticiEkrani();
        newyoneticiekrani.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_ProjeAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_ProjeAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_ProjeAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_ProjeAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_ProjeAra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRbtn_projelerimde;
    private javax.swing.JRadioButton jRbtn_tümprojelerde;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
