/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje_takip;

import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JFrm_CalisanEkrani extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_ScreenStaff
     */
    DefaultTableModel dtm_teslimEdilmiş = new DefaultTableModel();
    DefaultTableModel dtm_TeslimEdilmemis = new DefaultTableModel();
    public static SimpleDateFormat sdf = new SimpleDateFormat("dd.MMM.yyyy");
    List<Gorev_1> gorevler;

    public JFrm_CalisanEkrani() {

        initComponents();
        
        Date tarih = new Date();
        
        jbtn_teslimet.setEnabled(false);
        setTitle(JFrm_GirisEkrani.c_logined.getCalisanAdi() + " " + JFrm_GirisEkrani.c_logined.getCalisanSoyadi());
        Toolkit kit = Toolkit.getDefaultToolkit();
        int EkranY = (int) kit.getScreenSize().width; //Ekran boyutunun genişliğini alıyoruz...
        int EkranX = (int) kit.getScreenSize().height;//Ekran boyutunun yüksekliğini alıyoruz...
        this.setSize(930, 470); // Pencere boyutunu belirliyoruz...
        this.setLocation((EkranY - 470) / 2, (EkranX - 470) / 2);

        dtm_teslimEdilmiş.setColumnIdentifiers(new String[]{"Görev Id", "Proje Id ", "Görev Adı", "Veriliş Tarihi", "Son Teslim Tarihi", "Teslim Edilme Tarihi"});
        jtbl_TeslimEdilmisProjeler.setModel(dtm_teslimEdilmiş);
        dtm_TeslimEdilmemis.setColumnIdentifiers(new String[]{"Gorev Id", "Proje Id", "Görev Adı", "Veriliş Tarihi", "Son Teslim Tarihi"});
        jtbl_teslimEdilmemisProjeler.setModel(dtm_TeslimEdilmemis);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
        EntityManager em = emf.createEntityManager();

        Query q = em.createQuery("SELECT g FROM Gorev_1 g WHERE g.calisanId=:id");
        q.setParameter("id", JFrm_GirisEkrani.c_logined.getCalisanId());
        gorevler = q.getResultList();

        for (Gorev_1 gorev : gorevler) {
            if (gorev.getGorevTeslimTarihi() == null) {
                dtm_TeslimEdilmemis.addRow(new Object[]{gorev.getGorevId(), gorev.getProjeId(), gorev.getGorevAdi(),
                    sdf.format(gorev.getGorevVerilisTarihi()), sdf.format(gorev.getGorevTeslimEdilmesiGerekenTarih()), (gorev.getGorevTeslimTarihi())});
            } else if (gorev.getGorevTeslimTarihi() != null) {
                dtm_teslimEdilmiş.addRow(new Object[]{gorev.getGorevId(), gorev.getProjeId(), gorev.getGorevAdi(),
                    sdf.format(gorev.getGorevVerilisTarihi()), sdf.format(gorev.getGorevTeslimEdilmesiGerekenTarih()), sdf.format(gorev.getGorevTeslimTarihi())});
            }
        }

        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\ProjeTakip\\Gecmis.txt", true));
            bw.write(JFrm_GirisEkrani.c_logined.getCalisanId()+" Id'li çalışanın giriş Tarihi : "+tarih );

            bw.newLine();
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(JFrm_CalisanEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_teslimEdilmemisProjeler = new javax.swing.JTable();
        jbtn_teslimet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_TeslimEdilmisProjeler = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbl_teslimEdilmemisProjeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbl_teslimEdilmemisProjeler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_teslimEdilmemisProjelerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_teslimEdilmemisProjeler);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 218));

        jbtn_teslimet.setText("Teslim Et");
        jbtn_teslimet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_teslimetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_teslimet, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 216, 47));

        jTabbedPane1.addTab("Teslim Edilmemiş Görevler", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbl_TeslimEdilmisProjeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbl_TeslimEdilmisProjeler);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 212));

        jTabbedPane1.addTab("Teslim Edilmiş Görevler", jPanel1);

        jMenu1.setText("Çıkış");

        jMenuItem1.setText("Ana Ekrana Dön");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jbtn_teslimetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_teslimetActionPerformed
        // TODO add your handling code here:
        Date tarih = new Date();
        Gorev_1 gorev = null;
        int gorevId = Integer.parseInt(jtbl_teslimEdilmemisProjeler.getValueAt(jtbl_teslimEdilmemisProjeler.getSelectedRow(), 0).toString());
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1521221034_MeryemEzber_Odev1PU");
        EntityManager em = emf.createEntityManager();

        Query q1 = em.createQuery("SELECT g FROM Gorev_1 g WHERE g.gorevId = :gorevId");
        q1.setParameter("gorevId", gorevId);
        gorev = (Gorev_1) q1.getSingleResult();

        Query q2 = em.createQuery("UPDATE Gorev_1 g SET g.gorevTeslimTarihi=:teslimTarihi WHERE g.gorevId=:gorevId");
        q2.setParameter("teslimTarihi", tarih);
        q2.setParameter("gorevId", gorev.getGorevId());

        em.getTransaction().begin();
        q2.executeUpdate();
        em.getTransaction().commit();

        dtm_TeslimEdilmemis.setRowCount(0);
        dtm_teslimEdilmiş.setRowCount(0);

        EntityManager em2 = emf.createEntityManager();
        Query q3 = em2.createQuery("SELECT g FROM Gorev_1 g WHERE g.calisanId=:id");
        q3.setParameter("id", JFrm_GirisEkrani.c_logined.getCalisanId());
        gorevler = q3.getResultList();

        for (Gorev_1 g : gorevler) {
            if (g.getGorevTeslimTarihi() == null) {
                dtm_TeslimEdilmemis.addRow(new Object[]{g.getGorevId(), g.getProjeId(), g.getGorevAdi(),
                    sdf.format(g.getGorevVerilisTarihi()), sdf.format(g.getGorevTeslimEdilmesiGerekenTarih()), (g.getGorevTeslimTarihi())});
            } else if (g.getGorevTeslimTarihi() != null) {
                dtm_teslimEdilmiş.addRow(new Object[]{g.getGorevId(), g.getProjeId(), g.getGorevAdi(),
                    sdf.format(g.getGorevVerilisTarihi()), sdf.format(g.getGorevTeslimEdilmesiGerekenTarih()), sdf.format(g.getGorevTeslimTarihi())});
            }
        }

        jbtn_teslimet.setEnabled(false);

    }//GEN-LAST:event_jbtn_teslimetActionPerformed

    private void jtbl_teslimEdilmemisProjelerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_teslimEdilmemisProjelerMouseClicked
        // TODO add your handling code here:
        jbtn_teslimet.setEnabled(true);
    }//GEN-LAST:event_jtbl_teslimEdilmemisProjelerMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrm_GirisEkrani newgirisekrani = new JFrm_GirisEkrani();
        newgirisekrani.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrm_CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrm_CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrm_CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrm_CalisanEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrm_CalisanEkrani().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtn_teslimet;
    private javax.swing.JTable jtbl_TeslimEdilmisProjeler;
    private javax.swing.JTable jtbl_teslimEdilmemisProjeler;
    // End of variables declaration//GEN-END:variables
}
